package common;

/**
 *
 * Represents a response from the application.
 *
 * The Response enum contains various responses that can be received from the
 * application, each with a response name and a response number.
 */

public enum Response {
	FOUND_QUESTIONS("FOUND_QUESTIONS", 0), DIDNT_FOUND_QUESTIONS("DIDNT_FOUND_QUESTIONS", 1),
	EDIT_QUESTIONS_SUCCESS("EDIT_QUESTIONS_SUCCESS", 2), EDIT_QUESTIONS_FAILD("EDIT_QUESTIONS_FAILD", 3),
	UPDATE_CONNECTION_SUCCESS("UPDATE_CONNECTION_SUCCESS", 4), UPDATE_CONNECTION_FAILD("UPDATE_CONNECTION_FAILD", 5),
	LOGIN_SUCCESS("LOGIN_SUCCESS", 6), LOGIN_FAILURE_notInDB("LOGIN_FAILURE_notInDB", 7),
	LOGIN_FAILURE_loggedIn("LOGIN_FAILURE_loggedIn", 8), GET_GRADES_SUCCESS("GET_GRADES_SUCCESS", 9),
	GET_GRADES_FAILURE("GET_GRADES_FAILURE", 10), LOGOUT_SUCCESS("LOGUT_SUCCESS", 11),
	LOGOUT_FAILURE("LOGUT_FAILURE", 12), GET_COURSES_SUCCESS("GET_COURSES_SUCCESS", 13),
	GET_COURSES_FAILURE("GET_COURSES_FAILURE", 14), GET_TESTS_OF_COURSE_SUCCESS("GET_TESTS_OF_COURSE_SUCCESS", 15),
	GET_TESTS_OF_COURSE_FAILURE("GET_TESTS_OF_COURSE_FAILURE", 16),
	GENERATE_LECTURER_REPORT_SUCCESS("GENERATE_LECTURER_REPORT_SUCCESS", 17),
	GENERATE_LECTURER_REPORT_FAILURE("GENERATE_LECTURER_REPORT_FAILURE", 18),
	GET_DB_TABLE_SUCCESS("GET_DB_TABLE_SUCCESS", 19), GET_DB_TABLE_FAILURE("GET_DB_TABLE_FAILURE", 20),
	ADD_QUESTION_SUCCSESS("ADD_QUESTION_SUCCSESS", 21), ADD_QUESTION_FAILURE("ADD_QUESTION_FAILURE", 21),
	FOUND_TESTS("FOUND_TESTS", 22), DIDNT_FOUND_TESTS("DIDNT_FOUND_TESTS", 23), UPLOAD_SUCCESS("UPLOAD_SUCCESS", 24),
	GET_TEST_ID_SUCCESS("GET_TEST_ID_SUCCESS", 25), GET_TEST_ID_FAILURE("GET_TEST_ID_FAILURE", 26),
	GET_LISTS_SUCCESS("GET_LISTS_SUCCESS", 27), GET_LISTS_FAILURE("GET_LISTS_FAILURE", 28),
	GENERATE_DEP_HEAD_REPORT_SUCCESS("GENERATE_DEP_HEAD_REPORT_SUCCESS", 29),
	GENERATE_DEP_HEAD_REPORT_FAILURE("GENERATE_DEP_HEAD_REPORT_FAILURE", 30),
	GET_REQUESTS_SUCCESS("GET_REQUESTS_SUCCESS", 31), GET_REQUESTS_FAILURE("GET_REQUESTS_FAILURE", 32),
	UPDATE_REQUESTS_SUCCESS("UPDATE_REQUESTS_SUCCESS", 33), UPDATE_REQUESTS_FAILURE("UPDATE_REQUESTS_FAILURE", 34),
	FOUND_MAX_CODE_QUESTION("FOUND_MAX_CODE_QUESTION", 35),
	DIDNT_FOUND_max_code_question("DIDNT_FOUND_max_code_question", 36), GET_IP_SUCCESS("GET_IP_SUCCESS", 37),
	GET_QUESTION_TABLE_SUCCESS("GET_QUESTION_TABLE_SUCCESS", 38),
	GET_QUESTION_TABLE_FAILURE("GET_QUESTION_TABLE_FAILURE", 39), UPDATE_SUCCESS("UPDATE_SUCCESS", 40),
	UPDATE_FAILURE("UPDATE_FAILURE", 41), GET_STATUS_TEST_SUCCESS("GET_STATUS_TEST_SUCCESS", 42),
	GET_STATUS_TEST_FAILD("GET_STATUS_TEST_FAILD", 43), GET_REQUEST_TEST_SUCCESS("GET_REQUEST_TEST_SUCCESS", 44),
	GET_REQUEST_TEST_FAILD(" GET_REQUEST_TEST_FAILD", 45), SELECTED_QUESTIONS_SUCCESS("SELECTED_QUESTIONS_SUCCESS", 46),
	SELECTED_QUESTIONS_FAILURE("SELECTED_QUESTIONS_FAILURE", 47),
	ADD_TEST_POINTS_SUCCESS("ADD_TEST_POINTS_SUCCESS", 48), ADD_TEST_POINTS_FAILURE("ADD_TEST_POINTS_FAILURE", 49),
	ADD_TEST_SUCCESS("ADD_TEST_SUCCESS", 50), ADD_TEST_FAILURE("ADD_TEST_FAILURE", 51),
	FOUND_MAX_NUM_TEST("FOUND_MAX_NUM_TEST", 52), DIDNT_FOUND_max_NUM_TEST("DIDNT_FOUND_max_NUM_TEST", 53);
	;

	private String responeName;
	private int responeNumber;

	/**
	 * Constructs a Response enum value.
	 *
	 * @param responseName   The name of the response.
	 * @param responseNumber The number of the response.
	 */
	private Response(final String responeName, final int responeNumber) {
		this.responeName = responeName;
		this.setResponeNumber(responeNumber);
	}

	/**
	 * Retrieves the name of the response.
	 *
	 * @return The name of the response.
	 */
	public String toString() {
		return this.responeName;
	}

	/**
	 * Retrieves the number of the response.
	 *
	 * @return The number of the response.
	 */
	public int getResponeNumber() {
		return responeNumber;
	}

	/**
	 * Sets the number of the response.
	 *
	 * @param responeNumber The number of the response.
	 */
	public void setResponeNumber(int responeNumber) {
		this.responeNumber = responeNumber;
	}
}
